<?php
/**
 * @file
 * webintl_core.features.filter.inc
 */

/**
 * Implements hook_filter_default_formats().
 */
function webintl_core_filter_default_formats() {
  $formats = array();

  // Exported format: Plain text
  $formats['plain_text'] = array(
    'format' => 'plain_text',
    'name' => 'Plain text',
    'cache' => '1',
    'status' => '1',
    'weight' => '10',
    'filters' => array(
      'pathologic' => array(
        'weight' => '-50',
        'status' => '1',
        'settings' => array(
          'local_paths' => '/',
          'absolute' => 0,
        ),
      ),
      'filter_html_escape' => array(
        'weight' => '0',
        'status' => '1',
        'settings' => array(),
      ),
      'filter_url' => array(
        'weight' => '1',
        'status' => '1',
        'settings' => array(
          'filter_url_length' => '72',
        ),
      ),
      'filter_autop' => array(
        'weight' => '2',
        'status' => '1',
        'settings' => array(),
      ),
      'filter_htmlcorrector' => array(
        'weight' => '10',
        'status' => '1',
        'settings' => array(),
      ),
    ),
  );

  return $formats;
}
